### ISSUE TITLE
[scripts.web.injections/google-tasks] Issues

### ISSUE THREAD

**Issue by shawnfunke** [shawnfunke/shawnfunke#6]
#### Description

A list of current issues that need to be fixed for the Google Tasks injection.

#### Tasks

  - [ ] Fix styling for selection
  - [ ] Fix styling for input fields
  - [ ] Fix styling of date input
  - [ ] Fix styling of context menu ripple
  - [ ] Fix description wrap when 3 lines exist but the second one is left empty
  - [ ] Fix styling for task hovering
  - [ ] Fix description mutator when new tasks are added
